/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BrujulaRouteImport } from './routes/brujula'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TareasIndexRouteImport } from './routes/tareas.index'
import { Route as EquipoIndexRouteImport } from './routes/equipo.index'
import { Route as EntregasIndexRouteImport } from './routes/entregas.index'
import { Route as ClientesIndexRouteImport } from './routes/clientes.index'
import { Route as TareasTimelineRouteImport } from './routes/tareas.timeline'
import { Route as TareasTablaRouteImport } from './routes/tareas.tabla'
import { Route as ProyectosIdRouteImport } from './routes/proyectos.$id'
import { Route as PersonasIdRouteImport } from './routes/personas.$id'
import { Route as EquipoFechasRouteImport } from './routes/equipo.fechas'
import { Route as EquipoCargaRouteImport } from './routes/equipo.carga'
import { Route as EquipoCalendarioRouteImport } from './routes/equipo.calendario'
import { Route as EntregasTablaRouteImport } from './routes/entregas.tabla'
import { Route as EntregasKanbanRouteImport } from './routes/entregas.kanban'
import { Route as EntregasGanttRouteImport } from './routes/entregas.gantt'
import { Route as EntregasIdRouteImport } from './routes/entregas.$id'
import { Route as ClientesTarjetasRouteImport } from './routes/clientes.tarjetas'
import { Route as ClientesTablaRouteImport } from './routes/clientes.tabla'
import { Route as ClientesIdRouteImport } from './routes/clientes.$id'

const BrujulaRoute = BrujulaRouteImport.update({
  id: '/brujula',
  path: '/brujula',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TareasIndexRoute = TareasIndexRouteImport.update({
  id: '/tareas/',
  path: '/tareas/',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipoIndexRoute = EquipoIndexRouteImport.update({
  id: '/equipo/',
  path: '/equipo/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntregasIndexRoute = EntregasIndexRouteImport.update({
  id: '/entregas/',
  path: '/entregas/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesIndexRoute = ClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => rootRouteImport,
} as any)
const TareasTimelineRoute = TareasTimelineRouteImport.update({
  id: '/tareas/timeline',
  path: '/tareas/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const TareasTablaRoute = TareasTablaRouteImport.update({
  id: '/tareas/tabla',
  path: '/tareas/tabla',
  getParentRoute: () => rootRouteImport,
} as any)
const ProyectosIdRoute = ProyectosIdRouteImport.update({
  id: '/proyectos/$id',
  path: '/proyectos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonasIdRoute = PersonasIdRouteImport.update({
  id: '/personas/$id',
  path: '/personas/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipoFechasRoute = EquipoFechasRouteImport.update({
  id: '/equipo/fechas',
  path: '/equipo/fechas',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipoCargaRoute = EquipoCargaRouteImport.update({
  id: '/equipo/carga',
  path: '/equipo/carga',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipoCalendarioRoute = EquipoCalendarioRouteImport.update({
  id: '/equipo/calendario',
  path: '/equipo/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const EntregasTablaRoute = EntregasTablaRouteImport.update({
  id: '/entregas/tabla',
  path: '/entregas/tabla',
  getParentRoute: () => rootRouteImport,
} as any)
const EntregasKanbanRoute = EntregasKanbanRouteImport.update({
  id: '/entregas/kanban',
  path: '/entregas/kanban',
  getParentRoute: () => rootRouteImport,
} as any)
const EntregasGanttRoute = EntregasGanttRouteImport.update({
  id: '/entregas/gantt',
  path: '/entregas/gantt',
  getParentRoute: () => rootRouteImport,
} as any)
const EntregasIdRoute = EntregasIdRouteImport.update({
  id: '/entregas/$id',
  path: '/entregas/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesTarjetasRoute = ClientesTarjetasRouteImport.update({
  id: '/clientes/tarjetas',
  path: '/clientes/tarjetas',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesTablaRoute = ClientesTablaRouteImport.update({
  id: '/clientes/tabla',
  path: '/clientes/tabla',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesIdRoute = ClientesIdRouteImport.update({
  id: '/clientes/$id',
  path: '/clientes/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brujula': typeof BrujulaRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/clientes/tabla': typeof ClientesTablaRoute
  '/clientes/tarjetas': typeof ClientesTarjetasRoute
  '/entregas/$id': typeof EntregasIdRoute
  '/entregas/gantt': typeof EntregasGanttRoute
  '/entregas/kanban': typeof EntregasKanbanRoute
  '/entregas/tabla': typeof EntregasTablaRoute
  '/equipo/calendario': typeof EquipoCalendarioRoute
  '/equipo/carga': typeof EquipoCargaRoute
  '/equipo/fechas': typeof EquipoFechasRoute
  '/personas/$id': typeof PersonasIdRoute
  '/proyectos/$id': typeof ProyectosIdRoute
  '/tareas/tabla': typeof TareasTablaRoute
  '/tareas/timeline': typeof TareasTimelineRoute
  '/clientes/': typeof ClientesIndexRoute
  '/entregas/': typeof EntregasIndexRoute
  '/equipo/': typeof EquipoIndexRoute
  '/tareas/': typeof TareasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brujula': typeof BrujulaRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/clientes/tabla': typeof ClientesTablaRoute
  '/clientes/tarjetas': typeof ClientesTarjetasRoute
  '/entregas/$id': typeof EntregasIdRoute
  '/entregas/gantt': typeof EntregasGanttRoute
  '/entregas/kanban': typeof EntregasKanbanRoute
  '/entregas/tabla': typeof EntregasTablaRoute
  '/equipo/calendario': typeof EquipoCalendarioRoute
  '/equipo/carga': typeof EquipoCargaRoute
  '/equipo/fechas': typeof EquipoFechasRoute
  '/personas/$id': typeof PersonasIdRoute
  '/proyectos/$id': typeof ProyectosIdRoute
  '/tareas/tabla': typeof TareasTablaRoute
  '/tareas/timeline': typeof TareasTimelineRoute
  '/clientes': typeof ClientesIndexRoute
  '/entregas': typeof EntregasIndexRoute
  '/equipo': typeof EquipoIndexRoute
  '/tareas': typeof TareasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/brujula': typeof BrujulaRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/clientes/tabla': typeof ClientesTablaRoute
  '/clientes/tarjetas': typeof ClientesTarjetasRoute
  '/entregas/$id': typeof EntregasIdRoute
  '/entregas/gantt': typeof EntregasGanttRoute
  '/entregas/kanban': typeof EntregasKanbanRoute
  '/entregas/tabla': typeof EntregasTablaRoute
  '/equipo/calendario': typeof EquipoCalendarioRoute
  '/equipo/carga': typeof EquipoCargaRoute
  '/equipo/fechas': typeof EquipoFechasRoute
  '/personas/$id': typeof PersonasIdRoute
  '/proyectos/$id': typeof ProyectosIdRoute
  '/tareas/tabla': typeof TareasTablaRoute
  '/tareas/timeline': typeof TareasTimelineRoute
  '/clientes/': typeof ClientesIndexRoute
  '/entregas/': typeof EntregasIndexRoute
  '/equipo/': typeof EquipoIndexRoute
  '/tareas/': typeof TareasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/brujula'
    | '/clientes/$id'
    | '/clientes/tabla'
    | '/clientes/tarjetas'
    | '/entregas/$id'
    | '/entregas/gantt'
    | '/entregas/kanban'
    | '/entregas/tabla'
    | '/equipo/calendario'
    | '/equipo/carga'
    | '/equipo/fechas'
    | '/personas/$id'
    | '/proyectos/$id'
    | '/tareas/tabla'
    | '/tareas/timeline'
    | '/clientes/'
    | '/entregas/'
    | '/equipo/'
    | '/tareas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/brujula'
    | '/clientes/$id'
    | '/clientes/tabla'
    | '/clientes/tarjetas'
    | '/entregas/$id'
    | '/entregas/gantt'
    | '/entregas/kanban'
    | '/entregas/tabla'
    | '/equipo/calendario'
    | '/equipo/carga'
    | '/equipo/fechas'
    | '/personas/$id'
    | '/proyectos/$id'
    | '/tareas/tabla'
    | '/tareas/timeline'
    | '/clientes'
    | '/entregas'
    | '/equipo'
    | '/tareas'
  id:
    | '__root__'
    | '/'
    | '/brujula'
    | '/clientes/$id'
    | '/clientes/tabla'
    | '/clientes/tarjetas'
    | '/entregas/$id'
    | '/entregas/gantt'
    | '/entregas/kanban'
    | '/entregas/tabla'
    | '/equipo/calendario'
    | '/equipo/carga'
    | '/equipo/fechas'
    | '/personas/$id'
    | '/proyectos/$id'
    | '/tareas/tabla'
    | '/tareas/timeline'
    | '/clientes/'
    | '/entregas/'
    | '/equipo/'
    | '/tareas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrujulaRoute: typeof BrujulaRoute
  ClientesIdRoute: typeof ClientesIdRoute
  ClientesTablaRoute: typeof ClientesTablaRoute
  ClientesTarjetasRoute: typeof ClientesTarjetasRoute
  EntregasIdRoute: typeof EntregasIdRoute
  EntregasGanttRoute: typeof EntregasGanttRoute
  EntregasKanbanRoute: typeof EntregasKanbanRoute
  EntregasTablaRoute: typeof EntregasTablaRoute
  EquipoCalendarioRoute: typeof EquipoCalendarioRoute
  EquipoCargaRoute: typeof EquipoCargaRoute
  EquipoFechasRoute: typeof EquipoFechasRoute
  PersonasIdRoute: typeof PersonasIdRoute
  ProyectosIdRoute: typeof ProyectosIdRoute
  TareasTablaRoute: typeof TareasTablaRoute
  TareasTimelineRoute: typeof TareasTimelineRoute
  ClientesIndexRoute: typeof ClientesIndexRoute
  EntregasIndexRoute: typeof EntregasIndexRoute
  EquipoIndexRoute: typeof EquipoIndexRoute
  TareasIndexRoute: typeof TareasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/brujula': {
      id: '/brujula'
      path: '/brujula'
      fullPath: '/brujula'
      preLoaderRoute: typeof BrujulaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tareas/': {
      id: '/tareas/'
      path: '/tareas'
      fullPath: '/tareas/'
      preLoaderRoute: typeof TareasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipo/': {
      id: '/equipo/'
      path: '/equipo'
      fullPath: '/equipo/'
      preLoaderRoute: typeof EquipoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entregas/': {
      id: '/entregas/'
      path: '/entregas'
      fullPath: '/entregas/'
      preLoaderRoute: typeof EntregasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/': {
      id: '/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof ClientesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tareas/timeline': {
      id: '/tareas/timeline'
      path: '/tareas/timeline'
      fullPath: '/tareas/timeline'
      preLoaderRoute: typeof TareasTimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tareas/tabla': {
      id: '/tareas/tabla'
      path: '/tareas/tabla'
      fullPath: '/tareas/tabla'
      preLoaderRoute: typeof TareasTablaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyectos/$id': {
      id: '/proyectos/$id'
      path: '/proyectos/$id'
      fullPath: '/proyectos/$id'
      preLoaderRoute: typeof ProyectosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personas/$id': {
      id: '/personas/$id'
      path: '/personas/$id'
      fullPath: '/personas/$id'
      preLoaderRoute: typeof PersonasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipo/fechas': {
      id: '/equipo/fechas'
      path: '/equipo/fechas'
      fullPath: '/equipo/fechas'
      preLoaderRoute: typeof EquipoFechasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipo/carga': {
      id: '/equipo/carga'
      path: '/equipo/carga'
      fullPath: '/equipo/carga'
      preLoaderRoute: typeof EquipoCargaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipo/calendario': {
      id: '/equipo/calendario'
      path: '/equipo/calendario'
      fullPath: '/equipo/calendario'
      preLoaderRoute: typeof EquipoCalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entregas/tabla': {
      id: '/entregas/tabla'
      path: '/entregas/tabla'
      fullPath: '/entregas/tabla'
      preLoaderRoute: typeof EntregasTablaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entregas/kanban': {
      id: '/entregas/kanban'
      path: '/entregas/kanban'
      fullPath: '/entregas/kanban'
      preLoaderRoute: typeof EntregasKanbanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entregas/gantt': {
      id: '/entregas/gantt'
      path: '/entregas/gantt'
      fullPath: '/entregas/gantt'
      preLoaderRoute: typeof EntregasGanttRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entregas/$id': {
      id: '/entregas/$id'
      path: '/entregas/$id'
      fullPath: '/entregas/$id'
      preLoaderRoute: typeof EntregasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/tarjetas': {
      id: '/clientes/tarjetas'
      path: '/clientes/tarjetas'
      fullPath: '/clientes/tarjetas'
      preLoaderRoute: typeof ClientesTarjetasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/tabla': {
      id: '/clientes/tabla'
      path: '/clientes/tabla'
      fullPath: '/clientes/tabla'
      preLoaderRoute: typeof ClientesTablaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/$id': {
      id: '/clientes/$id'
      path: '/clientes/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof ClientesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrujulaRoute: BrujulaRoute,
  ClientesIdRoute: ClientesIdRoute,
  ClientesTablaRoute: ClientesTablaRoute,
  ClientesTarjetasRoute: ClientesTarjetasRoute,
  EntregasIdRoute: EntregasIdRoute,
  EntregasGanttRoute: EntregasGanttRoute,
  EntregasKanbanRoute: EntregasKanbanRoute,
  EntregasTablaRoute: EntregasTablaRoute,
  EquipoCalendarioRoute: EquipoCalendarioRoute,
  EquipoCargaRoute: EquipoCargaRoute,
  EquipoFechasRoute: EquipoFechasRoute,
  PersonasIdRoute: PersonasIdRoute,
  ProyectosIdRoute: ProyectosIdRoute,
  TareasTablaRoute: TareasTablaRoute,
  TareasTimelineRoute: TareasTimelineRoute,
  ClientesIndexRoute: ClientesIndexRoute,
  EntregasIndexRoute: EntregasIndexRoute,
  EquipoIndexRoute: EquipoIndexRoute,
  TareasIndexRoute: TareasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
